# Docker compose file for the application.

version: '3'
services:
  solr:
    image: solr:7.4.0
    ports:
      - "8983:8983"
    command: /opt/solr/bin/solr start -f -s /solr_home/
    volumes:
      - ./solr_home:/solr_home

  setup:
    build:
      context: .
      dockerfile: ./deploy/setup/Dockerfile
    links:
      - solr
    depends_on:
     - solr
